// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: AOSProject_2/project2.proto

package AOSProject_2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Num   uint64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Nodes string `protobuf:"bytes,3,opt,name=nodes,proto3" json:"nodes,omitempty"`
	Flag  string `protobuf:"bytes,4,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *Key) Reset() {
	*x = Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AOSProject_2_project2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_AOSProject_2_project2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_AOSProject_2_project2_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Key) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Key) GetNodes() string {
	if x != nil {
		return x.Nodes
	}
	return ""
}

func (x *Key) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

type Wkey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  *Key   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Low  uint64 `protobuf:"varint,3,opt,name=low,proto3" json:"low,omitempty"`
	Mid  uint64 `protobuf:"varint,4,opt,name=mid,proto3" json:"mid,omitempty"`
	High uint64 `protobuf:"varint,5,opt,name=high,proto3" json:"high,omitempty"`
}

func (x *Wkey) Reset() {
	*x = Wkey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AOSProject_2_project2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wkey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wkey) ProtoMessage() {}

func (x *Wkey) ProtoReflect() protoreflect.Message {
	mi := &file_AOSProject_2_project2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wkey.ProtoReflect.Descriptor instead.
func (*Wkey) Descriptor() ([]byte, []int) {
	return file_AOSProject_2_project2_proto_rawDescGZIP(), []int{1}
}

func (x *Wkey) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Wkey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wkey) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Wkey) GetMid() uint64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *Wkey) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

type CResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res string `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *CResponse) Reset() {
	*x = CResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AOSProject_2_project2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CResponse) ProtoMessage() {}

func (x *CResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AOSProject_2_project2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CResponse.ProtoReflect.Descriptor instead.
func (*CResponse) Descriptor() ([]byte, []int) {
	return file_AOSProject_2_project2_proto_rawDescGZIP(), []int{2}
}

func (x *CResponse) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

type DResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DResponse) Reset() {
	*x = DResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AOSProject_2_project2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DResponse) ProtoMessage() {}

func (x *DResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AOSProject_2_project2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DResponse.ProtoReflect.Descriptor instead.
func (*DResponse) Descriptor() ([]byte, []int) {
	return file_AOSProject_2_project2_proto_rawDescGZIP(), []int{3}
}

type WRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res uint64 `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *WRResponse) Reset() {
	*x = WRResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AOSProject_2_project2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WRResponse) ProtoMessage() {}

func (x *WRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AOSProject_2_project2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WRResponse.ProtoReflect.Descriptor instead.
func (*WRResponse) Descriptor() ([]byte, []int) {
	return file_AOSProject_2_project2_proto_rawDescGZIP(), []int{4}
}

func (x *WRResponse) GetRes() uint64 {
	if x != nil {
		return x.Res
	}
	return 0
}

func (x *WRResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type ARRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ARRead) Reset() {
	*x = ARRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AOSProject_2_project2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ARRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARRead) ProtoMessage() {}

func (x *ARRead) ProtoReflect() protoreflect.Message {
	mi := &file_AOSProject_2_project2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARRead.ProtoReflect.Descriptor instead.
func (*ARRead) Descriptor() ([]byte, []int) {
	return file_AOSProject_2_project2_proto_rawDescGZIP(), []int{5}
}

func (x *ARRead) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ARReadRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Low     uint64 `protobuf:"varint,3,opt,name=low,proto3" json:"low,omitempty"`
	Mid     uint64 `protobuf:"varint,4,opt,name=mid,proto3" json:"mid,omitempty"`
	High    uint64 `protobuf:"varint,5,opt,name=high,proto3" json:"high,omitempty"`
	Pval    string `protobuf:"bytes,6,opt,name=pval,proto3" json:"pval,omitempty"`
	Fval    string `protobuf:"bytes,7,opt,name=fval,proto3" json:"fval,omitempty"`
	Counter uint64 `protobuf:"varint,8,opt,name=counter,proto3" json:"counter,omitempty"`
	Msg     string `protobuf:"bytes,9,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ARReadRes) Reset() {
	*x = ARReadRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AOSProject_2_project2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ARReadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARReadRes) ProtoMessage() {}

func (x *ARReadRes) ProtoReflect() protoreflect.Message {
	mi := &file_AOSProject_2_project2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARReadRes.ProtoReflect.Descriptor instead.
func (*ARReadRes) Descriptor() ([]byte, []int) {
	return file_AOSProject_2_project2_proto_rawDescGZIP(), []int{6}
}

func (x *ARReadRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ARReadRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ARReadRes) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *ARReadRes) GetMid() uint64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *ARReadRes) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *ARReadRes) GetPval() string {
	if x != nil {
		return x.Pval
	}
	return ""
}

func (x *ARReadRes) GetFval() string {
	if x != nil {
		return x.Fval
	}
	return ""
}

func (x *ARReadRes) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *ARReadRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ARRollbackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Low     uint64 `protobuf:"varint,3,opt,name=low,proto3" json:"low,omitempty"`
	Mid     uint64 `protobuf:"varint,4,opt,name=mid,proto3" json:"mid,omitempty"`
	High    uint64 `protobuf:"varint,5,opt,name=high,proto3" json:"high,omitempty"`
	Pval    string `protobuf:"bytes,6,opt,name=pval,proto3" json:"pval,omitempty"`
	Fval    string `protobuf:"bytes,7,opt,name=fval,proto3" json:"fval,omitempty"`
	Counter uint64 `protobuf:"varint,8,opt,name=counter,proto3" json:"counter,omitempty"`
	Writer  string `protobuf:"bytes,9,opt,name=writer,proto3" json:"writer,omitempty"`
	Reader  string `protobuf:"bytes,10,opt,name=reader,proto3" json:"reader,omitempty"`
}

func (x *ARRollbackReq) Reset() {
	*x = ARRollbackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AOSProject_2_project2_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ARRollbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARRollbackReq) ProtoMessage() {}

func (x *ARRollbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_AOSProject_2_project2_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARRollbackReq.ProtoReflect.Descriptor instead.
func (*ARRollbackReq) Descriptor() ([]byte, []int) {
	return file_AOSProject_2_project2_proto_rawDescGZIP(), []int{7}
}

func (x *ARRollbackReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ARRollbackReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ARRollbackReq) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *ARRollbackReq) GetMid() uint64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *ARRollbackReq) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *ARRollbackReq) GetPval() string {
	if x != nil {
		return x.Pval
	}
	return ""
}

func (x *ARRollbackReq) GetFval() string {
	if x != nil {
		return x.Fval
	}
	return ""
}

func (x *ARRollbackReq) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *ARRollbackReq) GetWriter() string {
	if x != nil {
		return x.Writer
	}
	return ""
}

func (x *ARRollbackReq) GetReader() string {
	if x != nil {
		return x.Reader
	}
	return ""
}

type ARWriteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ARWriteRes) Reset() {
	*x = ARWriteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AOSProject_2_project2_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ARWriteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARWriteRes) ProtoMessage() {}

func (x *ARWriteRes) ProtoReflect() protoreflect.Message {
	mi := &file_AOSProject_2_project2_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARWriteRes.ProtoReflect.Descriptor instead.
func (*ARWriteRes) Descriptor() ([]byte, []int) {
	return file_AOSProject_2_project2_proto_rawDescGZIP(), []int{8}
}

func (x *ARWriteRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ARWrite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Low     uint64 `protobuf:"varint,3,opt,name=low,proto3" json:"low,omitempty"`
	Mid     uint64 `protobuf:"varint,4,opt,name=mid,proto3" json:"mid,omitempty"`
	High    uint64 `protobuf:"varint,5,opt,name=high,proto3" json:"high,omitempty"`
	Pval    string `protobuf:"bytes,6,opt,name=pval,proto3" json:"pval,omitempty"`
	Fval    string `protobuf:"bytes,7,opt,name=fval,proto3" json:"fval,omitempty"`
	Counter uint64 `protobuf:"varint,8,opt,name=counter,proto3" json:"counter,omitempty"`
	Flag    string `protobuf:"bytes,9,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *ARWrite) Reset() {
	*x = ARWrite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AOSProject_2_project2_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ARWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARWrite) ProtoMessage() {}

func (x *ARWrite) ProtoReflect() protoreflect.Message {
	mi := &file_AOSProject_2_project2_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARWrite.ProtoReflect.Descriptor instead.
func (*ARWrite) Descriptor() ([]byte, []int) {
	return file_AOSProject_2_project2_proto_rawDescGZIP(), []int{9}
}

func (x *ARWrite) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ARWrite) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ARWrite) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *ARWrite) GetMid() uint64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *ARWrite) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *ARWrite) GetPval() string {
	if x != nil {
		return x.Pval
	}
	return ""
}

func (x *ARWrite) GetFval() string {
	if x != nil {
		return x.Fval
	}
	return ""
}

func (x *ARWrite) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *ARWrite) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

var File_AOSProject_2_project2_proto protoreflect.FileDescriptor

var file_AOSProject_2_project2_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x41, 0x4f, 0x53, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2f, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x41,
	0x4f, 0x53, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x22, 0x51, 0x0a, 0x03, 0x4b,
	0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x6e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x77,
	0x0a, 0x04, 0x57, 0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x41, 0x4f, 0x53, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x32, 0x2e, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6c, 0x6f,
	0x77, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x6d, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x22, 0x1d, 0x0a, 0x09, 0x43, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x0b, 0x0a, 0x09, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x30, 0x0a, 0x0a, 0x57, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x72, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x18, 0x0a, 0x06, 0x41, 0x52, 0x52, 0x65, 0x61, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0xbb, 0x01, 0x0a, 0x09, 0x41, 0x52, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x6c, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x76, 0x61,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x76, 0x61, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x76, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x76, 0x61,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xdd, 0x01,
	0x0a, 0x0d, 0x41, 0x52, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x76, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x76, 0x61, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x76, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x76, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x1e, 0x0a,
	0x0a, 0x41, 0x52, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xbb, 0x01,
	0x0a, 0x07, 0x41, 0x52, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6d, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x76, 0x61, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x76, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x76, 0x61,
	0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x76, 0x61, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x32, 0x98, 0x04, 0x0a, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x11, 0x2e, 0x41, 0x4f, 0x53, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x32, 0x2e, 0x4b, 0x65, 0x79, 0x1a, 0x17, 0x2e, 0x41, 0x4f, 0x53, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2e, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0a, 0x77, 0x72, 0x69, 0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x12, 0x2e, 0x41, 0x4f, 0x53, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2e,
	0x57, 0x6b, 0x65, 0x79, 0x1a, 0x18, 0x2e, 0x41, 0x4f, 0x53, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x32, 0x2e, 0x57, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3a, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x11, 0x2e,
	0x41, 0x4f, 0x53, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2e, 0x4b, 0x65, 0x79,
	0x1a, 0x18, 0x2e, 0x41, 0x4f, 0x53, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2e,
	0x57, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x09,
	0x64, 0x72, 0x6f, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x11, 0x2e, 0x41, 0x4f, 0x53, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2e, 0x4b, 0x65, 0x79, 0x1a, 0x17, 0x2e, 0x41,
	0x4f, 0x53, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2e, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0c, 0x77, 0x72, 0x69, 0x74, 0x65,
	0x41, 0x52, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x15, 0x2e, 0x41, 0x4f, 0x53, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2e, 0x41, 0x52, 0x57, 0x72, 0x69, 0x74, 0x65, 0x1a, 0x18,
	0x2e, 0x41, 0x4f, 0x53, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2e, 0x41, 0x52,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0b, 0x72, 0x65,
	0x61, 0x64, 0x41, 0x52, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x2e, 0x41, 0x4f, 0x53, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2e, 0x41, 0x52, 0x52, 0x65, 0x61, 0x64, 0x1a,
	0x17, 0x2e, 0x41, 0x4f, 0x53, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2e, 0x41,
	0x52, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0f, 0x72, 0x6f,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x52, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x2e,
	0x41, 0x4f, 0x53, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2e, 0x41, 0x52, 0x52,
	0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x41, 0x4f, 0x53,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2e, 0x41, 0x52, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x13, 0x72, 0x6f, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x44, 0x72, 0x6f, 0x70, 0x41, 0x52, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x2e,
	0x41, 0x4f, 0x53, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2e, 0x41, 0x52, 0x52,
	0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x41, 0x4f, 0x53,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x2e, 0x41, 0x52, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x41, 0x4f, 0x53, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AOSProject_2_project2_proto_rawDescOnce sync.Once
	file_AOSProject_2_project2_proto_rawDescData = file_AOSProject_2_project2_proto_rawDesc
)

func file_AOSProject_2_project2_proto_rawDescGZIP() []byte {
	file_AOSProject_2_project2_proto_rawDescOnce.Do(func() {
		file_AOSProject_2_project2_proto_rawDescData = protoimpl.X.CompressGZIP(file_AOSProject_2_project2_proto_rawDescData)
	})
	return file_AOSProject_2_project2_proto_rawDescData
}

var file_AOSProject_2_project2_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_AOSProject_2_project2_proto_goTypes = []interface{}{
	(*Key)(nil),           // 0: AOSProject_2.Key
	(*Wkey)(nil),          // 1: AOSProject_2.Wkey
	(*CResponse)(nil),     // 2: AOSProject_2.CResponse
	(*DResponse)(nil),     // 3: AOSProject_2.DResponse
	(*WRResponse)(nil),    // 4: AOSProject_2.WRResponse
	(*ARRead)(nil),        // 5: AOSProject_2.ARRead
	(*ARReadRes)(nil),     // 6: AOSProject_2.ARReadRes
	(*ARRollbackReq)(nil), // 7: AOSProject_2.ARRollbackReq
	(*ARWriteRes)(nil),    // 8: AOSProject_2.ARWriteRes
	(*ARWrite)(nil),       // 9: AOSProject_2.ARWrite
}
var file_AOSProject_2_project2_proto_depIdxs = []int32{
	0, // 0: AOSProject_2.Wkey.key:type_name -> AOSProject_2.Key
	0, // 1: AOSProject_2.Token.createToken:input_type -> AOSProject_2.Key
	1, // 2: AOSProject_2.Token.writeToken:input_type -> AOSProject_2.Wkey
	0, // 3: AOSProject_2.Token.readToken:input_type -> AOSProject_2.Key
	0, // 4: AOSProject_2.Token.dropToken:input_type -> AOSProject_2.Key
	9, // 5: AOSProject_2.Token.writeARToken:input_type -> AOSProject_2.ARWrite
	5, // 6: AOSProject_2.Token.readARToken:input_type -> AOSProject_2.ARRead
	7, // 7: AOSProject_2.Token.rollbackARToken:input_type -> AOSProject_2.ARRollbackReq
	7, // 8: AOSProject_2.Token.rollbackDropARToken:input_type -> AOSProject_2.ARRollbackReq
	2, // 9: AOSProject_2.Token.createToken:output_type -> AOSProject_2.CResponse
	4, // 10: AOSProject_2.Token.writeToken:output_type -> AOSProject_2.WRResponse
	4, // 11: AOSProject_2.Token.readToken:output_type -> AOSProject_2.WRResponse
	3, // 12: AOSProject_2.Token.dropToken:output_type -> AOSProject_2.DResponse
	8, // 13: AOSProject_2.Token.writeARToken:output_type -> AOSProject_2.ARWriteRes
	6, // 14: AOSProject_2.Token.readARToken:output_type -> AOSProject_2.ARReadRes
	8, // 15: AOSProject_2.Token.rollbackARToken:output_type -> AOSProject_2.ARWriteRes
	8, // 16: AOSProject_2.Token.rollbackDropARToken:output_type -> AOSProject_2.ARWriteRes
	9, // [9:17] is the sub-list for method output_type
	1, // [1:9] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_AOSProject_2_project2_proto_init() }
func file_AOSProject_2_project2_proto_init() {
	if File_AOSProject_2_project2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AOSProject_2_project2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AOSProject_2_project2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wkey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AOSProject_2_project2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AOSProject_2_project2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AOSProject_2_project2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WRResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AOSProject_2_project2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ARRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AOSProject_2_project2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ARReadRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AOSProject_2_project2_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ARRollbackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AOSProject_2_project2_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ARWriteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AOSProject_2_project2_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ARWrite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AOSProject_2_project2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AOSProject_2_project2_proto_goTypes,
		DependencyIndexes: file_AOSProject_2_project2_proto_depIdxs,
		MessageInfos:      file_AOSProject_2_project2_proto_msgTypes,
	}.Build()
	File_AOSProject_2_project2_proto = out.File
	file_AOSProject_2_project2_proto_rawDesc = nil
	file_AOSProject_2_project2_proto_goTypes = nil
	file_AOSProject_2_project2_proto_depIdxs = nil
}
